---
- hosts: gluster
  become: true

  vars_files:
    - gluster/vars.yml

  roles:
    - geerlingguy.firewall

  tasks:
    - name: Ensure dependencies are installed.
      apt:
        name: dirmngr
        state: present

    - name: Ensure PPA for GlusterFS is present.
      apt_repository:
        repo: 'ppa:gluster/glusterfs-{{ glusterfs_ppa_version }}'
        state: present
      register: glusterfs_ppa_added
      when: glusterfs_ppa_use

    - name: Ensure GlusterFS will reinstall if the PPA was just added.
      apt:
        name:
          - glusterfs-server
          - glusterfs-client
        state: absent
      when: glusterfs_ppa_added.changed
      tags: ['skip_ansible_lint']

    - name: Ensure GlusterFS is installed.
      apt:
        name:
          - glusterfs-server
          - glusterfs-client
        state: present
        default_release: "{{ glusterfs_default_release }}"
    - name: Ensure GlusterFS is started and enabled at boot.
      service: "name={{ glusterfs_daemon }} state=started enabled=yes"

    - name: Ensure Gluster brick and mount directories exist.
      file:
        path: "{{ item }}"
        state: directory
        mode: 0775
      with_items:
        - "{{ gluster_brick_dir }}"
        - "{{ gluster_mount_dir }}"

    - name: Configure Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        replicas: 2
        cluster: "{{ groups.gluster | join(',') }}"
        host: "{{ inventory_hostname }}"
        force: yes
      run_once: true

    - name: Ensure Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted